<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Разработка и дизайн сайтов</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="/css/reset.css">
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/fonts.css">
    <link rel="stylesheet" href="/css/menu.css">
    <link rel="stylesheet" href="/css/color.css">
    <link rel="stylesheet" href="/css/animate.css">
    <link rel="stylesheet" href="/css/secondary.css">
    <link rel="stylesheet" href="/css/popup.css">
    <link rel="stylesheet" href="/css/<?= Menu::$current_url ?>.css">

    <!-- include js files -->

    <script src="/js/jquery.min.js"></script>
    <script src="/js/main.js"></script>
    <script src="/js/main_portfolio.js"></script>
    <script src="/js/wow.min.js"></script>
    <script src="/js/contact_us.js"></script>
    <script src="/js/popup.js"></script>

    <script>
        var wow = new WOW().init();
    </script>
</head>
<body>
<div id="load_in_process"></div>
<header>
    <?php
    Menu::render_menu();
    Menu::render_scroll_menu()
    ?>

</header>
<div class="content_wrapper">
    <?= $content ?>
</div>
<footer>
    <div class="wrap">
        <div class="f_phones">
            <div>+38 (095) 2144 880</div>
            <div>+38 (095) 2144 880</div>
        </div>
        <div class="f_emails">
            <div>info@flitter.pro</div>
        </div>
        <div class="f_date">&copy; 2016, Flitter</div>
        <div class="f_contact_btn">
            <div class="show_more_btn" onclick="contactUs.show(this)">Оставить заявку</div>
        </div>
    </div>
</footer>
</body>
</html>