<div class="partition_label">
    Контакты
</div>
<section>
    <div class="contact_form wow slideInLeft">
        <div class="label">Оставить заявку</div>
        <div class="contact_form_fields">
            <div>
                <div class="title">* Ваше имя</div>
                <div class="data"><input class="input_field" type="text"></div>
            </div>
            <div>
                <div class="title">* Как с вами связаться?</div>
                <div class="data"><input class="input_field" type="text"></div>
            </div>
            <div>
                <div class="title">Комментарий</div>
                <div class="data">
                    <textarea class="input_field"></textarea>
                </div>
            </div>
        </div>
        <div class="send_form">
            <button class="button_gradient">Связаться с нами</button>
        </div>
    </div>
    <div class="contacts wow slideInRight">
        <div class="label">Мы с радостью ответим на любые вопросы</div>
        <div class="phones">
            <div class="title">По телефону:</div>
            <div class="data">
                <div>+38 (095) 2144 880</div>
                <div>+38 (095) 2144 880</div>
            </div>
        </div>
        <div class="email">
            <div class="title">Или по почте:</div>
            <div class="data">
                <div>info@flitter.pro</div>
            </div>
        </div>

    </div>
</section>