<header id="section_1" class="main_slider_img">
    <div class="main_slide_content">
        <?php
        Menu::render_menu();
        Menu::render_scroll_menu()
        ?>
        <div class="main_slider_text">
            Разработка<br> и дизайн <br>
            сайтов
        </div>
        <div class="main_scroll_down" onclick="arrowDownClick(this)">
            <img src="/img/icons/arrows/arrow_down.png" alt="arrow down">
        </div>
    </div>
</header>

<section id="section_2" class="page_slide">
    <div class="label">Услуги</div>
    <div class="services">
        <div class="site_develop section wow slideInLeft">
            <div class="head">
                <img src="/img/icons/develop/create_stite.png">
                <div>Разработка сайтов</div>
            </div>
            <div class="srv_text">
                Разработка сайтов-визиток, корпоративных
                сайтов и лендингов.
            </div>
            <div class="show_more_btn">
                <a href="/services/sites">Подробней</a>
            </div>
        </div>
        <div class="design_create section wow slideInRight">
            <div class="head">
                <img src="/img/icons/develop/create_design.png">
                <div>Дизайн</div>
            </div>
            <div class="srv_text">
                Создание уникального дизайна сайтов, редизайн,
                прототипирование, создание вайрфреймов, разработка
                логотипов и фирменных стилей, дизайн печатной продукции.
            </div>
            <div class="show_more_btn">
                <a href="/services/design">Подробней</a>
            </div>
        </div>
    </div>
    <div class="services_more_list_wrap">
        <div class="list_site_create">
            <div class="service_small_container wow flipInY">
                <div>
                    <img src="/img/icons/develop/site/simle.png">
                </div>
                <div class="label-price">
                    Сайт-визитка<br>
                    <span>от 200$</span>
                </div>
                <div class="short_text">
                    Сайт визитка — это лучшее решение по соотношению цена-качество
                </div>
                <div class="show_more_btn">
                    <a href="/services/sites/site-card">Подробней</a>
                </div>
            </div>
            <div class="service_small_container wow flipInY">
                <div>
                    <img src="/img/icons/develop/site/busines.png">
                </div>
                <div class="label-price">
                    Корпоративный сайт<br>
                    <span>от 400$</span>
                </div>
                <div class="short_text">
                    Сайт визитка — это лучшее решение по соотношению цена-качество
                </div>
                <div class="show_more_btn">
                    <a href="/services/sites/corporate-websites">Подробней</a>
                </div>
            </div>
            <div class="service_small_container wow flipInY">
                <div>
                    <img src="/img/icons/develop/site/landing.png">
                </div>
                <div class="label-price">
                    Лендинг<br>
                    <span>от 500$</span>
                </div>
                <div class="short_text">
                    Сайт визитка — это лучшее решение по соотношению цена-качество
                </div>
                <div class="show_more_btn">
                    <a href="/services/sites/landing">Подробней</a>
                </div>
            </div>
        </div>
        <div class="list_design_create">
            <div class="service_small_container wow flipInY">
                <div>
                    <img src="/img/icons/develop/design/site-design.png">
                </div>
                <div class="label-price">
                    Веб-дизайн и прототипирование<br>
                    <span>от 70$</span>
                </div>
                <div class="short_text">
                    Уникальный дизайн, редизайн, вайрфреймы и прототипы.
                </div>
                <div class="show_more_btn">
                    <a href="services/design/web-design">Подробней</a>
                </div>
            </div>
            <div class="service_small_container wow flipInY">
                <div>
                    <img src="/img/icons/develop/design/branding.png">
                </div>
                <div class="label-price">
                    Брендинг и айдентика<br>
                    <span>от 100$</span>
                </div>
                <div class="short_text">
                    Разработка логотипов и корпоративного стиля.
                </div>
                <div class="show_more_btn">
                    <a href="services/design/logotypes">Подробней</a>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="section_3" class="page_slide">
    <div class="label">Последние работы</div>
    <div id="short_portfolio">
        <script>
            mainPortfolio.showTiles('short_portfolio')
        </script>
    </div>
    <div class="show_all_works">
        <button class="button_gradient"><a href="/portfolio">Все работы</a></button>
    </div>
</section>

<section id="section_4" class="page_slide">
    <div class="form_wrap">
    <div class="contact_form wow slideInLeft">
        <div class="label">Оставить заявку</div>
        <div class="contact_form_fields">
            <div>
                <div class="title">* Ваше имя</div>
                <div class="data"><input class="input_field" type="text"></div>
            </div>
            <div>
                <div class="title">* Как с вами связаться?</div>
                <div class="data"><input class="input_field" type="text"></div>
            </div>
            <div>
                <div class="title">Комментарий</div>
                <div class="data">
                    <textarea class="input_field"></textarea>
                </div>
            </div>
            <div class="send_form">
                <button class="button_gradient"><a href="#">Связаться с нами</a></button>
            </div>
        </div>
    </div>
    <div class="contacts wow slideInRight">
        <div>
        <div class="label">Мы с радостью ответим на любые вопросы</div>
        <div class="phones">
            <div class="title">По телефону:</div>
            <div class="data">
                <div>+38 (095) 2144 880</div>
                <div>+38 (095) 2144 880</div>
            </div>
        </div>
        <div class="email">
            <div class="title">Или по почте:</div>
            <div class="data">
                <div>info@flitter.pro</div>
            </div>
        </div>
        </div>
    </div>
    </div>
</section>
