<div class="partition_label">
    Услуги
</div>
<div class="services_main_container">
    <div class="services_left_wrap">
        <div class="head">
            <img src="/img/icons/develop/create_stite.png">
            <div>Разработка сайтов</div>
        </div>
        <div class="info_text"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis hendrerit arcu.
                Cras dignissim nibh vel libero fringilla, a lacinia ligula semper. Donec porttitor mauris id lacus
                semper viverra. Pellentesque eleifend ligula in efficitur efficitur. Class aptent taciti sociosqu ad
                litora torquent per conubia nostra, per inceptos himenaeos. Integer ornare odio molestie, ultrices orci
                sit amet, consectetur ex. Vestibulum vestibulum tincidunt ultrices. Sed vehicula, eros a ultricies
                cursus, ante elit accumsan arcu, at sodales elit mi a nulla. Maecenas sapien arcu, dapibus sit amet
                semper ac, lacinia eu dolor. Donec interdum condimentum ornare. Vivamus vel lectus vulputate, tincidunt
                nisi non, dignissim dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
                ridiculus mus. Donec accumsan scelerisque odio, eget rutrum libero gravida semper. Quisque lacinia porta
                facilisis. Sed tincidunt, nisi quis pellentesque hendrerit, lorem dolor consectetur tellus, eget
                bibendum est nisi sed metus. Sed odio nisi, molestie sed feugiat a, luctus dictum mauris. </p></div>
        <div class="services_more_list_wrap">
            <div class="service_small_container wow flipInY">
                <div>
                    <img src="/img/icons/develop/site/simle.png">
                </div>
                <div class="label-price">
                    Сайт-визитка<br>
                    <span>от 200$</span>
                </div>
                <div class="short_text">
                    Сайт визитка — это лучшее решение по соотношению цена-качество
                </div>
                <div class="show_more_btn">
                    <a href="/services/sites/site-card">Подробней</a>
                </div>
            </div>
            <div class="service_small_container wow flipInY">
                <div>
                    <img src="/img/icons/develop/site/busines.png">
                </div>
                <div class="label-price">
                    Корпоративный сайт<br>
                    <span>от 400$</span>
                </div>
                <div class="short_text">
                    Сайт визитка — это лучшее решение по соотношению цена-качество
                </div>
                <div class="show_more_btn">
                    <a href="/services/sites/corporate-websites">Подробней</a>
                </div>
            </div>
            <div class="service_small_container wow flipInY">
                <div>
                    <img src="/img/icons/develop/site/landing.png">
                </div>
                <div class="label-price">
                    Лендинг<br>
                    <span>от 500$</span>
                </div>
                <div class="short_text">
                    Сайт визитка — это лучшее решение по соотношению цена-качество
                </div>
                <div class="show_more_btn">
                    <a href="/services/sites/landing">Подробней</a>
                </div>
            </div>
        </div>
    </div>
    <div class="separate_line"></div>
    <div class="services_right_wrap">
        <div class="head">
            <div>Дизайн</div>
            <img src="/img/icons/develop/create_design.png">
        </div>
        <div class="info_text">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis hendrerit arcu. Cras dignissim nibh
                vel libero fringilla, a lacinia ligula semper. Donec porttitor mauris id lacus semper viverra.
                Pellentesque eleifend ligula in efficitur efficitur. Class aptent taciti sociosqu ad litora torquent per
                conubia nostra, per inceptos himenaeos. Integer ornare odio molestie, ultrices orci sit amet,
                consectetur ex. Vestibulum vestibulum tincidunt ultrices. Sed vehicula, eros a ultricies cursus, ante
                elit accumsan arcu, at sodales elit mi a nulla. Maecenas sapien arcu, dapibus sit amet semper ac,
                lacinia eu dolor. Donec interdum condimentum ornare. Vivamus vel lectus vulputate, tincidunt nisi non,
                dignissim dolor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
                Donec accumsan scelerisque odio, eget rutrum libero gravida semper. Quisque lacinia porta facilisis. Sed
                tincidunt, nisi quis pellentesque hendrerit, lorem dolor consectetur tellus, eget bibendum est nisi sed
                metus. Sed odio nisi, molestie sed feugiat a, luctus dictum mauris. </p>
        </div>
        <div class="list_design_create">
            <div class="service_small_container wow flipInY">
                <div>
                    <img src="/img/icons/develop/design/site-design.png">
                </div>
                <div class="label-price">
                    Веб-дизайн и прототипирование<br>
                    <span>от 70$</span>
                </div>
                <div class="short_text">
                    Уникальный дизайн, редизайн, вайрфреймы и прототипы.
                </div>
                <div class="show_more_btn">
                    Подробней
                </div>
            </div>
            <div class="service_small_container wow flipInY">
                <div>
                    <img src="/img/icons/develop/design/branding.png">
                </div>
                <div class="label-price">
                    Брендинг и айдентика<br>
                    <span>от 100$</span>
                </div>
                <div class="short_text">
                    Разработка логотипов и корпоративного стиля.
                </div>
                <div class="show_more_btn">
                    Подробней
                </div>
            </div>
        </div>
    </div>
</div>